version: "3.9"

services:
  web:
    build: .
    command: ./scripts/run.sh
    env_file: .env
    depends_on:
      - worker
    networks:
      - coolify-internal

  worker:
    build: .
    command: python worker.py
    env_file: .env
    networks:
      - coolify-internal

networks:
  coolify-internal:
    external: true
    name: coolify
